# Generated by Django 5.2.7 on 2025-10-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_loan_loanrepayment_person_loan_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='txn_uuid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txn_uuid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
