# Generated by Django 5.2.7 on 2025-10-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_expense_txn_uuid_transaction_txn_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='txn_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
