# Generated by Django 5.2.7 on 2025-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_expense_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='txn_uuid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_uuid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
